spring.application.name=demo

server.port=8080

# Conexión Reactiva a MySQL con R2DBC
spring.r2dbc.url=r2dbc:mysql://127.0.0.1:3306/bd_ejemplo?useSSL=false&serverTimezone=UTC
spring.r2dbc.username=root